<?php

return [
//   "Bank Indonesia",

  "Bank Mandiri",
  "Bank Rakyat Indonesia (BRI)",
  "Bank Central Asia (BCA)",
  "Bank Negara Indonesia (BNI)",
  "Bank Tabungan Negara (BTN)",
  "Bank Syariah Indonesia (BSI)",

  "Bank CIMB Niaga",
  "Bank OCBC NISP",
  "Bank Danamon",
  "Permata Bank",
  "Bank Mega",
  "Bank Maybank Indonesia",
  "Bank Panin",
  "Bank Sinarmas",
  "Bank Artha Graha Internasional",
  "Bank Bukopin",
  "Bank Capital Indonesia",
  "Bank Bumi Arta",
  "Bank Maspion",
  "Bank Ganesha",
  "Bank Index Selindo",
  "Bank Victoria International",
  "Bank Multiarta Sentosa (MAS)",
  "Bank Jago",
  "Allo Bank",
  "Bank Aladin",

  "Bank DKI",
  "Bank BJB (Jawa Barat dan Banten)",
  "Bank Jatim",
  "Bank Jateng",
  "Bank Sumut",
  "Bank Sumsel Babel",
  "Bank Nagari",
  "Bank Riau Kepri",
  "Bank Kalbar",
  "Bank Kalsel",
  "Bank Kaltimtara",
  "Bank NTB",
  "Bank NTT",
  "Bank Sulselbar",
  "Bank SulutGo",
  "Bank Papua",
  "Bank Bengkulu",
  "Bank Lampung",
  "Bank Maluku Malut",
  "Bank Aceh",

  "Bank Aceh Syariah",
  "Bank BJB Syariah",
  "Bank Mega Syariah",
  "Bank Muamalat Indonesia",
  "Bank BCA Syariah",
  "Bank BTPN Syariah",
  "Panin Dubai Syariah Bank",
  "Bank Aladin Syariah",
  "Bank KB Bukopin Syariah",
  "Bank Nano Syariah",

  "Citibank Indonesia",
  "HSBC Indonesia",
  "Standard Chartered Bank Indonesia",
  "Bank of China Indonesia",
  "Bank of America Indonesia",
  "JPMorgan Chase Bank Indonesia",
  "MUFG Bank Indonesia",
  "Deutsche Bank Indonesia",
  "ICBC Indonesia",
  "China Construction Bank Indonesia",
  "UOB Indonesia",
  "DBS Indonesia"
];
